require 'open-uri'
require 'openssl'
require 'redcarpet'
require 'xmlrpc/client'
require 'yaml'

# open https
OpenSSL::SSL::VERIFY_PEER = OpenSSL::SSL::VERIFY_NONE

helpers do

  def reload_config
    $config_cnt = nil
  end

  def init_config
    @password = ENV['github2wp-pwd']

    # remote config
    if ENV['github2wp-config']
      config_cnt = $config_cnt || get_cnt_from_url(ENV['github2wp-config'])
      $config_cnt = config_cnt # cache
      @remote_config = ENV['github2wp-config']
    elsif File.exists?('config.yml')
      # local config
      config_cnt = open('config.yml').read
    end
    # if there is no config - empty @urls - just "try" page (see 'login' router)
    @config   = config_cnt ? YAML.load(config_cnt) : {}
    @blog_url = @config['blog'] ? 'http://' + @config['blog'] : ''
    @urls     = @config['urls'] || []
    @password = @password || @config['pass-word']
  end


  def publish_from_source_to_wordpress(source_url, blog_domain, wp_post_id, wp_login, wp_pwd)
    cnt  = get_cnt_from_url(source_url)
    html = markdown_to_html(cnt)
    # read more is '---'
    html.gsub!(/<hr>/, '<!--more-->')

    # add header
    html = get_html_header(source_url) + html + get_html_footer

    post = {}
    # post['title'] = '...'
    post['description'] = html
    publish_to_wp(blog_domain, wp_post_id, post, wp_login, wp_pwd)
  end

  def get_cnt_from_url(url)
    open(url).read
  end

  def markdown_to_html(cnt)
    markdown = Redcarpet::Markdown.new(Redcarpet::Render::HTML, :autolink => true, :space_after_headers => true)
    markdown.render(cnt)
  end

  def publish_to_wp(blog_domain, wp_post_id, post, wp_login, wp_pwd)
    connection = XMLRPC::Client.new(blog_domain, '/xmlrpc.php')
    connection.call('metaWeblog.editPost', wp_post_id, wp_login, wp_pwd, post, true)
  end

  def github_row_link_to_human(link)
    human = link.gsub('raw.github.com', 'github.com').gsub('/master/', '/blob/master/')
    human
  end

  def get_html_header(github_row_link)
    link = github_row_link_to_human(github_row_link)
    "<div align='right'><small><a target='_blank' href='#{link}'>original source</a></small></div>"
  end

  def get_html_footer
    "<div align='right'><small>auto generated by <a target='_blank' href='https://github.com/nemilya/github2wp'>github2wp</a></small></div>"
  end

end